dvyukov/go-fuzz

- go-fuzz-build/cover.go
go-fuzz-build instruments code with coverage data.  This caused line
numbers in crash output to be wrong.  By setting `printer.SourcePos` in
the printer configuration we get `//line` directives added to the code,
which results in the line numbers from the original code.
Fixes #32.
> go-fuzz-build: set printer.SourcePos

- go-fuzz/versifier/versifier.go
- go-fuzz/versifier/versifier_test.go
Add support for Key-Value node generation and structure extraction to
the versifier. Currently this only supports AlphaNumNode types as keys
and values, so numeric keys or values will not yet work.
I initially thought that AlphaNumNode would work for both numeric and alphanumeric, but that is not the case. The solution may be using the `BlockNode` instead of `AlphaNumNode` but I'm opening the PR to get feedback on whether that's the best approach before implementing it.
> Add Key-Value support to versifier

- go-fuzz/versifier/versifier.go
The append logic in structureKeyValueNode was incorrect and could result
in a slice out of range error (#42). Correctly insert KeyValNode into nn
and update nn length.
fixes #42
> Correct insert of KeyValNode into []Node

- go-fuzz/hub.go
- go-fuzz/master.go
To test set syncDeadline to a low value and make it a variable:
```go
// hub.go
var syncDeadline = 200 * time.Millisecond
```
In the master loop increase the deadline every time a slave dies.
```go
// master.go
func masterLoop(m *Master) {
//...
log.Printf("slave %v died", s.id)
delete(m.slaves, id)
syncDeadline *= 2
//...
}
```
Run and see the slave reconnecting to the master.
As noted in the commit, the error handling still needs to improve on both the master and slave side, but this is a start.
> Fix for #44

- examples/sqlparser/main.go
there appears to be no other source of nodes
in `sel`, so this is likely just copy&paste
gone wrong.
> examples/sqlparser: remove adding sel.From twice

- go-fuzz-build/cover.go
motivation:
> [...]/internal.pb.go:16323]: __go_fuzz_tmp declared and not used
the source is in cockroachdb/cockroach/proto/internal.pb.go
and is a switch statement with only the default case.
> avoid unused variable error

- go-fuzz/versifier/versifier.go
- go-fuzz/versifier/versifier_test.go
This should fix #55. It also allows parsing of key-value lists and key-value nodes within bracket nodes.
> versifier key-value structure panic fix and parsing order

- go-fuzz-build/main.go
> Remove target file before renaming on Windows.

- README.md
This also changes the previous line to use the correct import path.
> Trophy: Add "index out of range" in collectd.org/network.

- go-fuzz-build/main.go
Fixes #116
`internal/race` is a new package in Go 1.6, skip it.
> Don't instrument internal/race

- go-fuzz-dep/doc.go
> Fix type-o

- README.md
In the issue it isn't clear that it was found with go-fuzz but I was the initial reporter and it was found with go-fuzz.
> Add bug found in go-ipfs

- examples/gotypes/main.go
As of Oct 25, the old parser is gone.
> examples/gotypes: eliminate newparser flag

- go-fuzz-build/main.go
- $GOROOT/src vendors "golang_org/x/net", requires no slash prefix
when going all the way to the root; affects go1.7 packages which
import "net/http"
- windows fix: use / instead of os.PathSeparator, use strings.Join
instead of filepath.Join
The error message was "can't find imported package golang_org/x/net/http2/hpack", which lives under $GOROOT/src/vendor.
> go-fuzz-build: fix stdlib vendor, windows vendor

- go-fuzz-build/main.go
Please let me know if this is something that might be of interest and/or if you want me to expand further.
> go-fuzz-build: added support for '-tags'

- go-fuzz/main.go
This PR adds support for the `~` sign with the `-bin` and `-workdir` flags and replaces it with the full path. 
I didn't want to use `flag.Set` because it's quite error prone when changing the tag string names. At least this gives compiler errors if the variable changes.
> go-fuzz: expand home directory for -bin and -workdir flags

- README.md
Add a trophy for github.com/digitalocean/captainslog, our syslog parser.
> trophies: add github.com/digitalocean/captainslog

- examples/png/png.go
Go 1.9 added an BufferPool member to Encoder
> fixes build error in png example, g1.9

- examples/sqlparser/main.go
Specifically:
* Fixed the issues related to API changes.
* Changed to using the ParseNext() API (which can parse multiple statements).
* Changed to use the io.Reader interface.
* Added a class to artificially reduce the chunks that can be read, to increase the chance of buffer underrun/overrun errors.
> Updated the sqlparser fuzzer to use the latest version of the library.

- README.md
Addressed in https://golang.org/cl/107835.
> readme: mark #12657 as fixed

- go-fuzz-build/main.go
Added recently to Go tip. Without this line, the build program breaks as
expected:
$ go-fuzz-build mvdan.cc/sh
failed to execute go build: exit status 1
import cycle not allowed
package mvdan.cc/sh/go.fuzz.main
imports go-fuzz-dep
imports runtime
imports runtime/internal/math
imports go-fuzz-dep
> go-fuzz-build: ignore new runtime internal package

- go-fuzz-build/cover.go
- go-fuzz-build/main.go
I'm working on porting go-fuzz-build to use go/packages. I have it working fully locally, but it needs more cleanup before it can be mailed. It's a pretty major change, and hard to split into multiple independent commits.
So in the meantime, chip away at some easy cleanup noticed along the way that we can dispense.
> go-fuzz-build: minor code cleanup

- README.md
- go-fuzz-build/cover.go
- go-fuzz-build/main.go
- go-fuzz-defs/defs.go
- go-fuzz-dep/doc.go
- go-fuzz-dep/main.go
- go-fuzz-dep/sonar.go
- go-fuzz-dep/sys_posix.go
- go-fuzz-dep/sys_windows.go
- go-fuzz/cover.go
- go-fuzz/hub.go
- go-fuzz/main.go
- go-fuzz/worker.go
- internal/go-fuzz-types/types.go
golang.org/x/tools/go/packages is a new package designed to aid in
locating, parsing, and typechecking Go packages.
This change updates go-fuzz-build to use it.
This effectively resulted in a rewrite of go-fuzz-build/main.go.
Some benefits are:
* Improved performance. go-fuzz-build appears to be 2x faster on
first build, and 4x faster on subsequent builds.
This is due to several factors. One big one is the use of cached
type information.
And there are more performance improvements available;
see the TODOs in the code.
* More robust. Previously, the list of ignored packages had to be
updated every time the standard library changed.
Now the ignored packages are computed on the fly.
* More user-friendly. You can now invoke go-fuzz-build without
a package path; it assumes ".", and relative …
> go-fuzz-build: use go/packages

- go-fuzz/compare_amd64.go
- go-fuzz/compare_amd64.s
- go-fuzz/cover_test.go
- go-fuzz/cpu_amd64.go
- go-fuzz/cpu_amd64.s
The SSE2 implementation uses only instructions that are assumed
available by the Go runtime. It can thus be used anywhere.
AVX2 support is checked for at runtime.
Benchmark Go implementation vs previous asm
name                     old time/op  new time/op  delta
CompareCoverBody/easy-8  6.79ns ± 9%  3.35ns ± 1%  -50.73%  (p=0.000 n=10+10)
CompareCoverBody/hard-8  18.6µs ± 5%   9.1µs ± 3%  -51.00%  (p=0.000 n=10+10)
Benchmark previous asm vs SSE2 asm
name                     old time/op  new time/op  delta
CompareCoverBody/easy-8  3.35ns ± 1%  5.56ns ± 5%  +66.01%  (p=0.000 n=10+10)
CompareCoverBody/hard-8  9.12µs ± 3%  1.79µs ± 2%  -80.38%  (p=0.000 n=10+9)
Benchmark SSE2 asm vs AVX2 asm
name                     old time/op  new time/op  delta
CompareCoverBody/easy-8  5.56ns ± 5%  5.35ns …
> go-fuzz: add SSE2 and AVX2 implementations of compareCoverBody

- go-fuzz-build/main.go
The previous commit (3246052064f01d6ca883b347da119b8afa1f4be1)
inadvertently removed a line of code along with comments.
Restore it. Oooops.
> go-fuzz-build: copy tool dir again

- go-fuzz/internal/pcg/pcg.go
- go-fuzz/mutator.go
- go-fuzz/versifier/versifier.go
go-fuzz generates a lot of random numbers.
math/rand is a mediocre PRNG, is large, and has contention issues.
This is mostly the fault of the Go 1 compatibility promise.
Add a dedicated PRNG just for go-fuzz; it's just 100 lines of code.
Because a 64 bit period and 32 bit output is ample for go-fuzz,
we can use a small PCG generator.
This is higher quality and much faster:
This PCG's Uint32 method is 2x faster than math/rand,
and the Intn method is 3x faster.
It is also easier to use.
> go-fuzz: switch to a PCG PRNG

- go-fuzz/testee.go
As a data point, before this PR, fuzzing github.com/dvyukov/go-fuzz-corpus/png maxes out on my machine at around 16k execs/sec. After this PR, that increases to about 26k execs/sec.
Please review carefully; the "avoid the giant buffer" commit in particular is subtle.
> Optimize testee memory allocation

- .travis.yml
From the comment at the top of .travis.yml, there are currently two main sets of tests:
1. Running go-fuzz-build and go-fuzz on dvyukov/go-fuzz-corpus/png starting with an empty corpus, and it validates >1 entry appears in the corpus. This uses what was formerly the required arguments like -workdir and -bin.
2. Running go-fuzz-build and go-fuzz on dvyukov/go-fuzz/test, which contains some regression tests, etc. This uses the newer ability to not supply any required arguments to go-fuzz-build and go-fuzz.
The current plan is to follow-up with a subsequent PR that moves most of the testing logic to a presubmit.sh so that it is easier to validate outside of travis.
When testing it against current master (ee722ec from 2019-03-12), it currently passes on Linux and Mac while failing on Windows …
> travis: add initial support for travis

- go-fuzz-build/main.go
Windows does not allow you to overwrite an existing file during 'go build'.
@thepudds can you confirm that this fixes #224?
> go-fuzz-build: fix Windows build

- go-fuzz-build/cover.go
- go-fuzz-build/main.go
- go-fuzz-dep/cover.go
- go-fuzz-dep/main.go
This code used to set up CoverTab to point to a global array.
This is simpler, and allows the short-lived array to be GC'd.
cc @guidovranken -- want to take a look and confirm that this fixes things again? Sorry again about the breakage. I wielded the scalpel far too freely.
> go-fuzz-dep: ensure that CoverTab starts non-nil for libfuzzer

- README.md
Make the 'go get' command more specific. Fixes #235.
Add a note about disabling modules during go-fuzz-build.
> README: module-related fixes

- README.md
- go-fuzz-build/main.go
Updates #195
Updates google/oss-fuzz/pull#2188
I'm genuinely unsure what other consequences this change might have. But since our module support is busted anyway, I suspect that this will at least make things no worse, and may fix some builds.
> go-fuzz-build: set GO111MODULE=off while building

- go-fuzz-build/main.go
- go-fuzz/main.go
This is a follow-up to #237.
Updates #195
Updates google/oss-fuzz/pull#2188
> go-fuzz-build: set GO111MODULE=off for all go/packages calls

- .travis.yml
- go-fuzz/main.go
In travis, add tests for Go tip on linux and osx.
In tip and Go 1.13, `GO111MODULE` defaults to `on` (whereas it defaults to `auto` in 1.11 and 1.12). 
However, travis explicitly sets `GO111MODULE=auto`.  Therefore, when testing tip, we explicitly set `GO111MODULE=on` to give normal tip / 1.13 behavior.
Note: it does not work just to use `env: GO111MODULE=on` because then `go get` stops working (perhaps because `go-fuzz` is not yet a module).  Instead, we use `SET_GO111MODULE` in the travis configuration, and then check that to know whether or not to do `export GO111MODULE=on` just before invoking `go-fuzz-build` and `go-fuzz`.
Separately, pull request #237 was merged, but that current fix is probably incomplete for disabling modules. With these changes, travis passes with 1.11 and 1.12, …
> travis: also test go-fuzz with Go tip (including because oss-fuzz is using tip)

- go-fuzz-build/main.go
using os.Rename to move files fails when copying files between different
partitions. On Debian 10 it failes with an "invalid cross-device link"
error. The solution is to copy the source file to the destination and
then remove the source.
> Fix moving files

- go-fuzz-build/main.go
libfuzzer's generated main function uses package reflect.
When attempting to build a package that doesn't depend
on reflect, such as github.com/dvyukuv/go-fuzz-corpus/{bzip2,gif,url},
package reflect wasn't getting copied to GOROOT, and the build failed.
Fix that.
We may need something similar in the future for fuzz.F; see #223.
Updates google/oss-fuzz/#2188
> go-fuzz-build: load reflect when using libfuzzer

- README.md
After a recent move of the examples directory to a new location, the Readme needs to be updated to reflect this.
> Update location of examples in Readme

- go-fuzz/coordinator.go
Sometimes, when I restart go-fuzz in coordinator mode with several workers connected the coordinator crashes with the following error: 
```
panic: runtime error: integer divide by zero
goroutine 84 [running]:
main.(*Coordinator).coordinatorStats(0xc00013a200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:153 +0x2c9
main.(*Coordinator).broadcastStats(0xc00013a200)
/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:109 +0x43
main.coordinatorLoop(0xc00013a200)
/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:104 +0x177
created by main.coordinatorMain
/go/src/github.com/dvyukov/go-fuzz/go-fuzz/coordinator.go:67 +0x31b
```
I didn't dive too deep to find out why it happens, but pretty sure that in any case, we should …
> Fix integer division by zero in coordinator

- go-fuzz-build/main.go
When `go build` call from `go-build-fuzz` fails, it is convenient to run it with `-x` flag to get an idea of what went wrong.
Also, if both `-x` and `-work` flags are set, both of them are passing to `go build` call to keep all working directories.
> go-build-fuzz: add -x flag

- go-fuzz-build/main.go
The -preserve flag allows people to opt out of having
particular packages instrumented, either to work around issues
or to reduce coverage noise from uninteresting, large packages
early in the critical path.
Fixes #266
> go-fuzz-build: add -preserve flag

- go-fuzz-build/main.go
Package main is not importable, and go-fuzz-build requires
that we be able to import the package in question,
in order to be able to call the Fuzz function.
The existing error message did contain the relevant information,
but it was buried amidst a bunch of other noise. Make it clearer.
Error message before:
failed to execute go build: exit status 1
/var/folders/1t/n61cbvls5bl293bbb0zyypqw0000gn/T/go-fuzz-build699217618/gopath/src/github.com/dvyukov/go-fuzz-corpus/cmd/go.fuzz.main/main.go:5:2: import "github.com/dvyukov/go-fuzz-corpus/cmd" is a program, not an importable package
Error message after:
cannot fuzz package main
> go-fuzz-build: improve error when trying to fuzz package main

- go-fuzz-build/main.go
Hey Team,
I know a complete solution for go-fuzz modules support with comprehensive tests is under the works by @thepudds . In the meantime, a lot of people are blocked by this feature and I suggest adding this opt-in environment (`GOFUZZ111MODULES=on`) variable that I documented that it will go away.
cc @mvdan @josharian @dvyukov 
can you please review and approve if this is ok?
Cheers,
Yevgeny
> Add opt-in go-fuzz modules support

- README.md
Add a new entry to the list of trophies for an [off-by-one](https://en.wikipedia.org/wiki/Off-by-one_error)(?) issue I found in [gofuzz](https://github.com/google/gofuzz) (another fuzzing package for go that does purely random fuzzing). Not 100% if this qualifies but I figured it's worth a try :smiley:
> Add trophy to README

- README.md
fuzzit.dev was acquired by GitLab. 
Continuous fuzzing with go-fuzz is now supported on gitlab.com
> fuzzit.dev was acquired by GitLab!

- go-fuzz/testee.go
> go-fuzz: reorder Testee fields to fix 32 bit architectures

- go-fuzz-build/cover.go
> go-fuzz-build: set position of BinaryExpr in sonar

- README.md
The past link directs to "https://github.com/dvyukov/go-fuzz/blob/master/github.com/golang/go/wiki/Modules".
> Fix the link to Go Modules page

- .travis.yml
- go-fuzz-build/cover.go
- go-fuzz-build/main.go
- testscripts/fuzz_help.txt
- testscripts/mod_go_fuzz_dep.txt
- testscripts/mod_inside_gopath.txt
- testscripts/mod_outside_gopath.txt
- testscripts/mod_v2.txt
- testscripts/mod_vendor.txt
This PR hopefully addresses a couple of go-fuzz issues, while also updating tests to handle changes in cmd/go. Travis has been failing on master for go-fuzz for ~5 different reasons for several months, but with these changes, travis is now passing again on my fork.
* go-fuzz-build: 
* handle abi_amd64.h (new in go1.17) for #322.
* do not doubly preserve '//go:build' comments for #313.
* testscripts: 
* cmd/go now defaults to -mod=readonly, so explicitly add go-fuzz-dep via 'go get'.
* cmd/go now requires a valid go.sum entry, so use 'go get' rather than go.mod for go-fuzz-dep.
* '-h' no longer causes non-zero status code as of Go 1.15 or so.
* travis
* golang/go#44487 was likely causing go-fuzz travis tests to fail with tip for several months or so due to cmd/go panic, likely due to the …
> fix go-fuzz failing at Go tip, plus get testing passing again

- README.md
This PR adds [github.com/go-git/go-git](https://github.com/go-git/go-git) to the trophy list as I was able to find a bug causing an infinite loop in its revision parser with go-fuzz.
Thanks for a great tool!
> Add github.com/go-git/go-git to trophy list

- go-fuzz-build/main.go
I would like to propose a more general fix, but I only need this one for now, and it's a reasonably simple extension of what's done for `abi_amd64.h`
EDIT: I added a commit to look for all go:embeds in all packages, not just that specific one in the sdk.
> support go:embed, resolves dvyukov/go-fuzz#338, dvyukov/go-fuzz#326

- README.md
see https://go.dev/doc/go-get-install-deprecation
> README.md: using the `go install` instead of the `go get`

- go-fuzz-build/cover.go
Better would be to handle them.
But ignoring them is more useful than failing to build.
Fixes #246 (at least as much am I'm ever going to)
> go-fuzz-build: ignore invalid int literals
