README.md

Not that exciting maybe but still shows how powerfull this tool is.
I just created wav headers with zero samples as corpuses and directly hit these two panics.
Thanks for this awesome tool!

wav: 2 panics in header decoding

---

README.md

There are more areas to look, but leave that for another day.
Great tool, very easy to set up and use.

Add trophy report for Hugo

---

README.md

add gocql trophy

---

README.md

Change-Id: I99358bf0e923678fc171f285cd0a9a666f3d4567

Add trophy for golang.org/x/net/icmp

---

README.md

Signed-off-by: Tw <tw19881113@gmail.com>

fix blackfriday's index out of range issues

---

go-fuzz-dep/sys_posix.go
go-fuzz/sys_posix.go

Standard approach (go-fuzz-build of the binary, go-fuzz it later) works
pretty well on this OS.

Allow building on FreeBSD platform

---

README.md

Thanks very much for this amazing tool, @dvyukov !  I'm sure I'll find plenty of trophies to add for my other packages!

Add trophy for github.com/mdlayher/ethernet

---

README.md
go-fuzz/master.go

fix for the comment noted on [PR #38](https://github.com/dvyukov/go-fuzz/pull/38#issuecomment-125723580)

fixed index page for http server

---

README.md

Add trophy for github.com/mdlayher/aoe

---

README.md

gogo protobuf issue 86 fixed

---

README.md

Thank you for this great tool. Helped me find and fix 2 crashes when decompressing invalid input.

added github.com/pierrec/lz4 crashes

---

README.md

Added: image/png: slice bounds out of range #12545 to the list of trophies

Trophy Added

---

README.md

Awesome lib! Thanks for creating it.

Add one more trophy

---

README.md

README: mention fuzzing `main` is not supported

---

README.md

Thanks again for this amazing tool!

Add trophy for github.com/mdlayher/netlink

---

README.md

https://github.com/buger/goreplay/pull/411
Thank you!

Add trophy for github.com/buger/goreplay

---

go-fuzz/main.go

go-fuzz: expand homedir fix

---

README.md

I published a blog post yesterday about my experience with go-fuzz, called [Going down the rabbit hole with go-fuzz](https://mijailovic.net/2017/07/29/go-fuzz/). If you like it, you might consider accepting it to the list of external articles in README file.

Add a new external article

---

README.md

Thanks so much for this excellent tool. I was astonished at how simple this was to use.

Add github.com/spenczar/tdigest trophies

---

README.md

README: mention that go-fuzz outputs to stderr

---

README.md

Add github.com/mdlayher/ndp trophy

---

README.md

Add github.com/vcabbage/amqp trophy

---

go-fuzz-build/main.go

Default to `go env GOPATH` upon empty GOPATH (~/go)

---

go-fuzz-build/main.go
go-fuzz/sonar.go
go-fuzz/worker.go

See individual commits for details.

More odds and ends

---

go-fuzz-build/main.go
go-fuzz-dep/main.go
go-fuzz/main.go
go-fuzz/testee.go
go-fuzz/worker.go
internal/go-fuzz-types/types.go

This is a first step towards full support for fuzzing multiple functions simultaneously.
There are two commits, which should be read independently. The first is a cleanup commit that was important to do before the second commit made it more complicated.

Compile in multiple fuzz functions

---

go-fuzz-build/main.go

I'm not particularly happy about all the hard-coding of paths
required to make this work. One of the nice things about migrating
to go/packages was that we almost entirely stopped hard-coding
lists of packages. But unfortunately, I don't see an alternative here.
Updates #231

go-fuzz-build: add -race

---

go-fuzz/hub.go
go-fuzz/mutator.go
go-fuzz/worker.go

I'm continuing to upstream my local go-fuzz changes. This is another batch of little stuff.

Odds and ends improvements

---

go-fuzz-build/main.go

Go 1.13 has a new -trimpath flag to cmd/go.
It removes all path prefixes (GOROOT, GOPATH).
This will yield nicer panic tracebacks,
without the go-fuzz-build temp directories.
It will also allow go-fuzz-build to use the cmd/go cache.
It doesn't have a dramatic impact on build times,
but every little bit helps.
Note that upstream cache support for -trimpath is mildly broken,
but it will be fixed by the time Go 1.13 is released,
and in the meantime, adding -trimpath support to go-fuzz doesn't hurt.

go-fuzz-build: use -trimpath flag when available

---

.travis.yml

There seems to be some change in osx machine setup on travis.

.travis.yml: fix osx setup

---

README.md

See https://github.com/bookingcom/nanotube/pull/97.

add a trophy for github.com/bookingcom/nanotube

---

go-fuzz-build/main.go

pretty Context.copyDir()

---

README.md

One for [robfig/cron](https://github.com/robfig/cron) and one for [cronokirby/saferith](https://github.com/cronokirby/saferith)

Add two trophies

---

go-fuzz-build/main.go

- go-fuzz-build: gofmt main.go
- go-fuzz-build: copy abi_arm64.h
- go-fuzz-build: do not instrument package reflect

go-fuzz-build: fix two minor bugs

---

go-fuzz-build/cover.go
go-fuzz-build/main.go

- go-fuzz-build: add yet more positions
- go-fuzz-build: add even more positions

add more positions to fix build errors
